### ISSUE TITLE
The Cyrillic lower case Я (uni044F) is incorrect; upper case Ц (uni0426) and Ч (uni0427) look weird

### ISSUE THREAD

**Issue by StefanPeev** [ctrlcctrlv/kjv1611#1]
The Cyrillic lower case Я (uni044F) is incorrect. It should be turned round.

![kjv1611_cyrillic_uni044f](https://user-images.githubusercontent.com/12949369/39934361-35fea58e-554e-11e8-9f1c-993d1cb226f3.png)

**Comment by ctrlcctrlv** [comment]
Thank you - I will fix this in the next release. I also think Ц and Ч need some tweaks.

**Comment by StefanPeev** [comment]
Yes, the upper case Ц and Ч need some tweaks.

**Comment by ctrlcctrlv** [comment]
Does this look better to you? I appreciate your help. As far as I know, this font is unique. I couldn't find a single other Blackletter font that supported Cyrillic and Greek.

![image](https://user-images.githubusercontent.com/838783/40003240-6c3b2a7c-57c5-11e8-897f-a60dc34cc6a7.png)

**Comment by StefanPeev** [comment]
It's better now, but Ц (uni0426) looks much brighter inside than И, Ч, Ш, П for example. Think about it. Your font is nice. Congratulations! But the truth is that there are other Gothic fonts with Cyrillic. [Lombard](https://localfonts.eu/freefonts/decorative-cyrillic-free-fonts/lombard/) is still a project, but you could look at [Encient German Gothic](https://fonts2u.com/encient-german-gothic.font), [Fortuna Gothic FlorishC](http://bg.allfont.net/download/fortuna-gothic-florishc/), [Cyrillic Goth](http://fontoteka.com/font/cyrillic-goth). Gothic Rus, GothicCyr, Hermann Gotisch even Verona Gothic.

**Comment by ctrlcctrlv** [comment]
@StefanPeev While of course I would always prefer to be the first, I'm quite happy you were able to find such varied examples for me. I think I wasn't able to find them mostly due to their age and use of non-UTF8 encodings, so I really appreciate an actual end user of these fonts helping me find them.
