### ISSUE TITLE
Asterisk

### ISSUE THREAD

**Issue by artistofmind** [ctrlcctrlv/kjv1611#10]
The asterisk has two issues:
1. Its tips are square / blunt, but should be round / tapered.
2. It is perfectly straight, whereas it should tilt left by ~10 degrees.

**Comment by ctrlcctrlv** [comment]
I've determined this is valid and will fix it in the next version of the font.

**Comment by artistofmind** [comment]
Looking through those scans, I have noticed the central vertical axis of this character is the only part that really seems tilted; I believe the "x" it goes through stays level.

I also draw your attention again to the tips of the "spokes." It seems they are all quite rounded. Because yours are perfectly square, in contrast your asterisk appears thick / blunt / stubby. (Without necessarily being any of the above; just by contrast.)

I encourage you to peruse those scans, and see for yourself. This character occurs frequently, thanks to all the marginal notes; so you can easily find a few dozen samples, which I believe will corroborate these impressions.
