### ISSUE TITLE
Exclamation mark

### ISSUE THREAD

**Issue by artistofmind** [ctrlcctrlv/kjv1611#11]
The triangular exclamation mark has surely been invented for this font. But there is an actual exclamation mark in the Bible (cf. Num. 24:23). It has a straight shaft.

**Comment by ctrlcctrlv** [comment]
The "!" was indeed made just for this font.

See #3 for my advice on the non-gothic font in the KJV. Putting the "!" from the non-gothic font will make this one look out of place.

**Comment by artistofmind** [comment]
Your recommendation is to just use EB Garamond for this character? Well, I guess that yields satisfactory results. OK.
