### ISSUE TITLE
Hyphens

### ISSUE THREAD

**Issue by artistofmind** [ctrlcctrlv/kjv1611#12]
1. (I discovered the word-wrap hyphen is present & sufficient.)
2. Regular hyphens are a bit thick, and bent to either side. They should be thinner & straighter, or even vaguely dot-like. (Cf. most instances of the name Nebuchad-rezzar.)

**Comment by ctrlcctrlv** [comment]
I'm happy for your edit to (1), I was about to bring up myself that I do indeed have word-wrap hyphens in my font.

My hyphen (-) comes from "[right.jpg](https://github.com/ctrlcctrlv/kjv1611/blob/master/KJV%20glyphs/misc/right.jpg)". I will need an image to consider changing it, or adding an alternate.

**Comment by artistofmind** [comment]
OK. I will email you some crops from my scanned copy.

**Comment by ctrlcctrlv** [comment]
Thanks for your email! I will keep my hyphen as the regular hyphen since it better fits with the Gothic style, but I will add the hyphen in "Nebuchad-nezzar" as U+FE63 ("SMALL HYPHEN MINUS")

**Comment by Alice196498** [comment]
On further inſpection, it ſeems that the word-wrapping hyphen is too thin, and it therefore appears ſtrange next to the other letters.
 I’ve alſo noticed another iſſue, which is in my opinion more an iſſue with InDeſign than the fount itſelf, but I ſhall mention it nonetheleſs : InDeſign has a peculiar tendancy to uſe the ASCII hyphen-minus (U+002D) glyph with automatick hyphens ; thus, while I’d have to check ſome books in order to attempt to diſcern the moſt common practice, I think that it might be better to define U+002D as the double ſort, and let the Unicode hyphen (U+2010) be the one you have defined as hyphen-minus.

**Comment by artistofmind** [comment]
I second that suggestion. In general, it would be a good idea to (1) make the most commonly occuring variant of a given character the normal ASCII glyph; and, likewise, (2) make the most historically authentic version of that glyph the default one, and any inventions the alternates (rather than the other way around, as you seem wont to do). It just seems sensible, for a font which markets itself as a reproduction of this specific typeface.

That said, I don’t accuse you of anything like unwarranted pride. You do fine work; this is just my 2¢ concerning what constitutes a good policy. Of course I admit a bias, in that my own primary use for this typeface will be to digitally reproduce the book it’s derived from. Naturally then, my preference is for the historical / common variants, in each & every case.

That also said, you might consider releasing your font in two versions: the Historical one and the “Remastered” one. This way users have a choice of which characters will be the default, and which the alternates. Which might even be the only difference between the two “flavors.” :)

**Comment by artistofmind** [comment]
It seems I may have misread Alice’s comment yesterday. Alas, the double hyphen can’t be made default, as there _is_ a normal hyphen which occurs in some passages (e.g. in the name Nebuchad-rezzor), and I despair of finding & replacing all instances thereof with some obscure HTML entity. (When I said we should try to “make the most commonly occuring variant of a given character the normal ASCII glyph,” I meant the most average appearance of the normal hyphen, as opposed to Mr. Brennan’s re-imagined hyphen.) At least in Firefox (as opposed to ID), that double hyphen is automatically inserted exactly where it should go: only ever at the ends of lines. If you wish it to be an ASCII character rather than an entity, I propose the = sign (which I take it is currently an invention). If ID won’t auto-split words with an equals in them, simply insert a zero space after it (but I needn’t tell you how to do such things). ^_^ That said, I believe you are right about the thinness thereof; however, it’s actually close to what it should look like on average, so I advise restraint in thickening it. At most half again the thickness, I’d say.

Whereas the current default hyphen is quite a bit thicker, and longer, than any I’ve found in the original document. It is also bent, whereas all the ones I’ve seen are straight. I reiterate that, despite a month of hunting these things down and cropping them, I have yet to find a single one like it. They are mostly quite short; indeed, some are just dots — I believe the latter usually occur in areas with less space, whereas longer ones appear on more spacious lines — and the vast majority are also quite thin. (The thickest I’ve found was still thinner than the one in this font; and given that the adjacent letters were also on the thick side, I suspect it’s the result of inkbleed.) That said, he may _have_ to include alternate hyphens, at least for the dot-like variant. But I think the one with the most average appearance should be the default.

Re. my own suggestion last night, of compiling two versions of the typeface as a whole: How about calling the Remastered one KJV1611-R? (Or -N, for New; -A, for Alternate; -C, for Custom; U, for Updated — whatever you wish.) The actual name is up to you, but I propose a single letter, rather than another number, as that might prove confusing. I also think it’s unnecessary to add anything to the name of the Historical version, since the current name already reflects exactly what it purports to be. If one of them has an additional letter and the other doesn’t, people will know from the name alone which version they’re using; and it’s intuitive that the one with something added to the name should be the one with added glyphs. :)

Finally, it occurs to me that, rather than merely swap defaults & alternates, you could just not bother with alternates at that point (unless they pertain to their respective versions). The normal version need have none but authentic glyphs, and the custom version can have whatever new glyphs or tweaks seem fitting to you.

**Comment by ctrlcctrlv** [comment]
As I see it, the purposes of this font are:

1. To *revive* and *remaster* the typeface found in the 1611 version of the King James Bible, [hitherto never digitized](http://www.typophile.com/node/104422);
1. To provide a *high-quality*, *free*, and *open-source* blackletter typeface in the English style, of which [few to none currently exist](https://fontlibrary.org/en/search?category=blackletter&order=);
1. To *encode all unique glyphs* in the blackletter typeface found in the 1611 KJV;
1. To provide a *historically accurate* font to cater to the needs of producing an exact reproduction of the 1611 King James Bible;
1. To encode as many glyphs from as many languages as possible in the style of the KJV: Greek, Russian, Romanian, &c.

When these desires conflict, ones higher on the priority list are what I stick to. I view &numero;4 as a highly desirable project, yet a niche usage of this font. Therefore I disagree that historical accuracy should always be default. After all, users working on a project like &numero;4 are much more likely to know how to use OpenType alternates and advanced typographic features than users who are just using this font and expect sensible, modern metrics and matching weights between letters.

I've considered in the past releasing a Historical Forms version of this font, but I feel that given my current build process it will result in me duplicating too much work. I would much rather fix this problem with OpenType than with different versions of the font for each need. Perhaps I could make a Stylistic Set that would replace all of my "innovations" with `.notdef` or something along those lines.
