### ISSUE TITLE
d

### ISSUE THREAD

**Issue by artistofmind** [ctrlcctrlv/kjv1611#13]
The left-facing tip of the ascender on the lowercase "d" should be slightly rounded, rather than perfectly square. (Cf. your scan, or nearly any verse.)

**Comment by ctrlcctrlv** [comment]
I'm torn about this. I can see slight rounding in "[He Bible.jpg](https://github.com/ctrlcctrlv/kjv1611/blob/master/KJV%20glyphs/misc/He%20Bible.jpg)", but I think my square version looks better.

**Comment by artistofmind** [comment]
I know that feeling: that's how I feel about the perfectly weighted small caps in your LORD ligature vs. the faked small caps (same weight, smaller point size) in the original. In that case, I prefer yours, too! ^_^ But, above all else, I value accuracy. At least, to the extent your project & mine overlap, that's my whole attraction to your typeface, is that it's the most accurate reproduction I have found. (And >90% perfect, BTW. I sincerely hope my criticisms are all constructive.)
Perhaps a compromise: just _very slightly_ round the corners, and leave the center line straight. It seems to me this would be in keeping with most of the other letters in your font. For example, the lowercase "f." You could just do what you've done on the edge of its "hook" with the "d," facing the other way. :)

**Comment by ctrlcctrlv** [comment]
![dd](https://user-images.githubusercontent.com/838783/52711273-640e3f80-2fcc-11e9-85ed-02ea3c5b983d.png)

I've added an alternate `d`, but left mine as the default in https://github.com/ctrlcctrlv/kjv1611/commit/b1e88eae23318f0890f393d690741ecc1f5e7fa9 :smile:
