### ISSUE TITLE
Paragraph symbol

### ISSUE THREAD

**Issue by artistofmind** [ctrlcctrlv/kjv1611#15]
The &para; glyph could stand to be thinner, and more symmetrical. In most examples I've found, the inside line and top & bottom curves are all one thickness, which in turn matches the weight of the parentheses, and possibly the inner strokes of some capital letters. (I haven't used a microscope, but this is my considered impression, based on comparing many different pages.)
      Whereas, at the moment, yours is slightly bottom-heavy, and on the thick side — suggesting ink bleed in your sample.
      If you simply matched the top & bottom to the center stroke (no taper toward the tips), this may suffice. It's possible even the center could be just a hair thinner, but I leave that to your judgment.
      I think this may be the last less-than-perfect thing I can find in your faithful reproduction of this beautiful typeface. I thank you heartily & soulfully for your attention to detail, and modesty when confronted with criticism. (You have already done a better job than I could ever have, myself, so I feel guilty bringing any of these perceived flaws to your attention.) Thank you for sharing this labor of love with the world. God bless you!

**Comment by ctrlcctrlv** [comment]
Thank you once again for your kind comments :-)

I found the paragraph symbol unusually difficult to find good examples of in my reproduction Bible, so much so I used two images to make it, "KJV glyphs/symbols/¶2.jpg" and "KJV glyphs/symbols/¶.jpg".

Please provide a better image (or vector) if you have one. I can use any SVG vector in the font if you know how to edit those.

**Comment by ctrlcctrlv** [comment]
I'm going to mark this one confirmed since it's easy to see it's overly thick, at least in the first example.

![para](https://user-images.githubusercontent.com/838783/50722558-043e9200-110c-11e9-827d-9d121e68c353.png)

**Comment by artistofmind** [comment]
In your facsimile, try Gen. 2:8.
I’ll also send you some crops from my Furness Collection scans. They are JPEG and it’s an old book, so there are still flaws, but different ones from those in the Greatsite facsimile. It’s unfortunate the former is now offline; I have the whole thing though, so if you’re interested, perhaps I can manage to upload all 1504 pages somewhere temporarily so you can see if you find any subtle details missing from the harsh two-color-only treatment of that facsimile. :)

**Comment by ctrlcctrlv** [comment]
Here's a new pilcrow in red, old in blue. What do you think @artistofmind ?

![pilcrow](https://user-images.githubusercontent.com/838783/51829688-0e2d6c80-2329-11e9-96e9-84d3a7f91ff0.png)

**Comment by artistofmind** [comment]
I think it looks much better! Well done.

**Comment by artistofmind** [comment]
In fact, this is better than I’d hoped!

At first I thought the top & bottom arcs were perfectly symmetrical; however, in cropping this character from scans a few hundred times (give or take) — searching for the most pristine dozen or so — I have noticed the bottom tip often has that little uptick. It’s really hard to tell _exactly_ how their tips should be shaped relative to each other, since the pressings vary so widely, but I think the slight angles & curves in yours are extremely well chosen. This is as faithful as anything could be to the original design (reverse engineered as it must be), and it’s æsthetically pleasing to a higher degree than any scan of an olde booke could be. In this case I will admit that, if anything, you’ve improved on the original. :)

I’m also thrilled to find there’s already a new release! This has come much sooner than I expected. I understand it’s not yet final, but thank you for keeping us updated. I really appreciate that you’ve worked so hard on this. I’m downloading the master now!

Thanks again!
