### ISSUE TITLE
Capital letters

### ISSUE THREAD

**Issue by artistofmind** [ctrlcctrlv/kjv1611#17]
A few of the capital letters need minor tweaks. In particular:

• Your “A” has a perfectly straight crossbar, whereas the original is at a slight angle. (Cf. emailed pictures.)
• Your “B” is too wide. (Cf. ibid.)
• And your “N” is too tall. Not above the x height, but below it: its right foot should anchor on the baseline. (Type e.g. “Ne,” and the part facing the “e” should be in line with it.)

In the near future, I will attempt to reproduce a few more passages, which I will then paste side-by-side (or top-to-bottom) with a cropped scan of the original, and send you a screenshot as before. The goal being to doublecheck the other capitals, too (and perhaps various other details). I will try to do this with multiple passages that feature the same characters, and in this way also doublecheck the source. (Since we know it varies slightly from letterpress to letterpress.)

Of course, now that you possess the same scans, you have the ability to do this as well. Though perhaps less free time. ;) But minor tweaks are easier to deal with than major overhauls or additions, and I hope that’s all that remains by the time you get to this issue. :)

**Comment by ctrlcctrlv** [comment]
Hey, thanks for your issue. I've decided to add alternate characters for the issues you pointed out. I know they are closer to the source, but I find them inferior to my innovated letters, which all have a regular weight and height. Now users can choose what they prefer: typographically superior letters, or historically accurate ones. Cheers!

![diff](https://user-images.githubusercontent.com/838783/52533713-cd931180-2d72-11e9-88a4-77e312252907.png)

**Comment by artistofmind** [comment]
I have an epic email pending. Been cropping a couple hundred letters per day, then deleting most of them. ;) The resulting (relatively pristine) crops make several things very plain. The size of your W is one of them. (I have a great crop which shows the capital & lowercase of that letter vertically right above / below each other! Cf. p. 908, top left, "whoꝛedome / Wherefore.") Another is the E has a curved vertical line on the inside, as do F / N at the bottom of their inside left stems (albeit very subtle curves by comparison); the J and L have perfectly symmetrical S-curves on their interior cutaways; the H has a dip between the arch & stem; the R in the LORD ligature is open at the top; etc., etc., etc. I have noticed a couple dozen things not yet mentioned on here! I have only procrastinated bringing these things to your attention because I want to finish compiling the evidence, first.

Rather than reproducing whole verses, this time what I'm working on is a side-by-side comparison of every character in your font vs. a dozen of the most pristine examples I can find of that same character from random pages in the original document. I'm more than halfway finished with this project, and apologize that it may take me a few more days before I'm ready to send you my work. But I believe it will be of greater benefit to you than anything I have submitted so far. :)

That said, I am pleased that you discovered the W size issue on your own. I'm sure you would eventually find all the rest of these details, too; the only point of my doing this is to help you!

God bless.

**Comment by ctrlcctrlv** [comment]
@artistofmind How are the alternate B, A, and E? They're in the latest build. :)

Glad to see you're still interested in the project! I commented on a few issues here but didn't hear back, for example #15

**Comment by artistofmind** [comment]
Oh! I’ve been checking here periodically, but I don’t get notifications, at least not at my primary email address. I guess I should fix that.

Here’s one more quirk I’ve noticed: the vertical lines inside the capital G tilt right slightly, and the vertical lines inside the capital O tilt left slightly. You can verify they aren’t perfectly straight by comparing them to the sides of other letters nearby.

**Comment by artistofmind** [comment]
The new capital N is much improved! 👍 Besides adjusting the height, I see you’ve also touched it up a bit. Well done, sir! Capital, indeed. ;)

That said, the crossbar actually goes all the way through the diamond. Cf. (e.g.) p. 920, v. 22 (bottom-left quadrant), or p. 470, v. 23 (top-right quadrant). I’ve cropped several hundred Ns, now (I think? I didn’t keep most, so it’s hard to say), and in most of them that crossbar is only partially visible, because the line is thin and the printing press just doesn’t do it justice on both sides half the time, only one or the other (or sometimes neither). But I’ve seen enough with a line to the left of the central “diamond” that I’m 100% confident it’s supposed to go all the way through.

Also, I didn’t find a single one with a crossbar between the thick & thin left stems! But I see you already removed that anomaly from your latest N. ;) Once again, I observe that my contributions are unnecessary — you’ll find all these things on your own — I’m just trying to help, and thus speed you along.
 
Cheers!
