### ISSUE TITLE
Sequence "longs longs_i" poorly kerned

### ISSUE THREAD

**Issue by ctrlcctrlv** [ctrlcctrlv/kjv1611#18]
Per https://github.com/ctrlcctrlv/kjv1611/issues/14#issuecomment-454225723

Also missing:

- longs longs_h
- longs longs_t

f_f followed by i, f, or t also missing but not an issue due to better default kerning of `f_f`.

**Comment by Alice196498** [comment]
The way this way implemented cauſes the ligatures not to appear, becauſe it’s being interpreted as longs_longs i, h, or t, which is not covered. In other words, longs_longs is not being kerned properly. It alſo ſeems that the kerning for long s followed by w is broken. As for the miſſing ffi ligature, while it is better, if one looks carefully, it’s quite clear that they are ſeparate.

![image](https://user-images.githubusercontent.com/30258857/51821640-3616d300-231d-11e9-831c-e78a6358c614.png)

**Comment by ctrlcctrlv** [comment]
I see, so you mean sequence `longs_longs i` is also poorly kerned...

**Comment by ctrlcctrlv** [comment]
Also @Alice196498 please make sure you have the latest version...there was a bug in one of my recent releases that disabled all kerns due to a FontForge bug, see https://github.com/ctrlcctrlv/kjv1611/commit/6bdea5fd158e6be8ba1a04a79bd62cf64607f6e9

**Comment by ctrlcctrlv** [comment]
![longs](https://user-images.githubusercontent.com/838783/51823144-7ecc8d00-2319-11e9-98c5-00fb365b86f7.png)

**Comment by ctrlcctrlv** [comment]
I've decided to just add three new glyphs and `liga` instructions:
```
sub longs longs h by longs_longs_h;
sub longs longs t by longs_longs_t;
sub longs longs i by longs_longs_i;
```
![triples](https://user-images.githubusercontent.com/838783/51840403-febd1c00-2346-11e9-94bb-8d5a219e3d41.png)
![fixed](https://user-images.githubusercontent.com/838783/51840442-12688280-2347-11e9-84fe-d04460be9ce8.png)

Not ideal, I know full well, but it does work. :-)

**Comment by ctrlcctrlv** [comment]
https://github.com/ctrlcctrlv/kjv1611/commit/6952ad19666237cb693dcaff2e98e2423ba44d4a
