### ISSUE TITLE
Where's the "ye" ligature?

### ISSUE THREAD

**Issue by CoreyMurray** [ctrlcctrlv/kjv1611#2]
Hello, I've downloaded your font and I like it, but there doesn't seem to be a "ye" ligature in the font.

As you no doubt are aware, the "ye" ligature stands for the word "the", the "y" being a substitute for the symbol "thorn", which did not exist in the typefaces the English imported from mainland Europe.

Are you planning to add the "ye" ligature in the future? If so, will it be a contextual ligature for use with OpenType capabilities?

Let us know as soon as possible.

**Comment by ctrlcctrlv** [comment]
@CoreyMurray I don't mind adding one, but I was not able to find one in the replica 1611 KJV I had

**Comment by CoreyMurray** [comment]
It's here: https://www.kingjamesbibleonline.org/John-Chapter-3_Original-1611-KJV/

**Comment by CoreyMurray** [comment]
What I meant to say is, I found a few pages in which the "ye" ligature/symbol (which consists of a lowercade "y" with a lowercade "e" above it) is located.

Here's a close-up of KJV 1611 ed. John ch 3 v 16 (it contains the "ye" symbol): https://imgur.com/a/I3Ug9un

**Comment by CoreyMurray** [comment]
Thanks for self-assigning this issue :) Looking forward to the revised fonts!

**Comment by ctrlcctrlv** [comment]
Sure, sorry for the delay, I haven't had time to research how I should add this as the "ye" ligature is not in Unicode; perhaps I should add it in the `hlig` (Historical Ligatures) table.

**Comment by ctrlcctrlv** [comment]
But I also want to make it easy for users to use without special software; maybe I will also add it to the PUA.

**Comment by CoreyMurray** [comment]
Sure, go ahead :)

**Comment by CoreyMurray** [comment]
Hi, me again, any progress on the revision?

**Comment by ctrlcctrlv** [comment]
Hello my friend, I very much apologize to you for the delay.

I got it working, at last.

![hlig](https://user-images.githubusercontent.com/838783/50533898-b4d9ee00-0b6e-11e9-90ed-1b7b1fced83b.png)
![nohlig](https://user-images.githubusercontent.com/838783/50533899-b7d4de80-0b6e-11e9-8faa-4dd48940787f.png)

You can expect the fix in sfnt revision 3.0.

**Comment by ctrlcctrlv** [comment]
Just a note, based on a suggestion from @Alice196498 (#14), this is going to be changing in sfnt revision 3.1.

It will no longer combine in `hlig`, but instead it will combine in two ways:

* Inside regular default `liga`, `y` followed by `uni0364` (COMBINING LATIN SMALL LETTER E, as yͤ).
* Inside `hlig`, `thorn` followed by `e` will form `ye`. (Inside `hist`, my invented `thorn` is dropped for `y` as well.)

**Comment by artistofmind** [comment]
It occurs quite rarely, but for example in [Ier. xlix:17](https://www.kingjamesbibleonline.org/1611_Jeremiah-Chapter-49/#17) (p. 871 -- not the best example in those scans, but the nearest to hand in my study today), there is also a "yt" ligature. Same principle as "ye," just short for "that" instead of "the."

I don't suppose you could duplicate what you did before, and add a yt ligature for thorn + t?
