### ISSUE TITLE
No stylistic sets

### ISSUE THREAD

**Issue by Alice196498** [ctrlcctrlv/kjv1611#23]
The hist feature is not available in moſt typeſetting foſtware ; thus, my ſuggeſtion is to include the features encoded there in ſeparate ſtyliſtick ſets ſo that they may be uſed in all programs that ſupport it.

**Comment by ctrlcctrlv** [comment]
Thank you for the suggestion, however it is available in:

* all modern browsers via CSS;
* Adobe software;
* LibreOffice ( https://twitter.com/HW_BEAT_THAT/status/1089780639883177984 );
* XeLaTeX / LuaLaTeX.

This is good enough for me, I prefer to retain `hist`.

**Comment by Alice196498** [comment]
I moſtly uſe InDeſign, and I’m pretty ſure it’s not available, but all right.

**Comment by ctrlcctrlv** [comment]
I did some research so decided to re-open this. *No promises, let's be clear...I might never get to this* but I suppose it is a valid issue. I renamed it also.

**Comment by Alice196498** [comment]
I ſhould like to write here to tell you that I think the work you do here is nothing leſs than amazing. The dedication and induſtry you diſplay in your ready willingneſs to liſten and work with people on theſe iſſues is ſomething I highly eſteem. You don’t have to do anything, but out of love and kindneſs, you tireleſsly work to improve your product, and provide it for everyone to uſe freely—that is ſomething which I’m ſure future people will note with great fondneſs and reſpect, juſt as I, and many others, do now. Thank you for everything you do.

**Comment by ctrlcctrlv** [comment]
Thank you, let me know if https://github.com/ctrlcctrlv/kjv1611/commit/8fa63b1adf03892d3ead0201bcfafcb9e5e803a3#diff-12f26e96265b26a767692f7833b875ed works for you in InDesign :)

**Comment by Alice196498** [comment]
I juſt teſted it—I didn’t know you could actually name ſtyliſtick ſets. What a uſeful feature !—and they all ſeem to work (although I amn’t ſure what the exact purpoſe of the firſt one is), but the hiſtorical forms aren’t replacing initial u with v. So while you have things like _euery_ and _heauen_ written properly, words ſuch as _vnto_ are written as _unto,_ for example. The i/j diſtinction is alſo not maintained : much like u and v, which were conſidered to be the ſame letter, but written differently depending on where it is (like the long s and ſhort s), i and j were thought of in the ſame manner. I think I talked about this in #4. The long s appears to be implemented about as correctly as it can be, aſide from the lack of kerning diſcuſſed in #29, wherein I didn’t think to mention long_longs_b, which would only ever be written ſsb or ſs-b to my knowledge, but that’s a very rare ſequence.
