### ISSUE TITLE
Missing U+A76D LATIN SMALL LETTER IS ꝭ

### ISSUE THREAD

**Issue by ctrlcctrlv** [ctrlcctrlv/kjv1611#24]
Per #14

**Comment by ctrlcctrlv** [comment]
Update: I have no idea how to handle the capital variant at A76C! I have emailed Michael Everson, who proposed these two characters, asking for help; [his proposal](https://www.unicode.org/L2/L2006/06027-n3027-medieval.pdf) did not include any proof this character exists, much less how I should represent it.

**Comment by Alice196498** [comment]
I’ve never ſeen it uſed in majuſcule form, only in the minuſcule. I’ve ſeen it in ſome old printing as well as handwriting, but even here, I’ve not ſeen a capital variant ; as far as I know, the only reaſon for its being included in the propoſal is that Unicode requires that both forms be preſent for newly added characters. As for how to repreſent it, I ſuppoſe it would juſt be a larger verſion of the minuſcule.
