### ISSUE TITLE
Missing ꝑ (U+A751)

### ISSUE THREAD

**Issue by ctrlcctrlv** [ctrlcctrlv/kjv1611#28]
Per #14 

Not found in the KJV, but cool nonetheless.

![p](https://user-images.githubusercontent.com/838783/53013149-fe183100-347f-11e9-9401-90070141be2f.png)

**Comment by dscorbett** [comment]
This looks to me like ⟨ꝑ⟩ (U+A751 LATIN SMALL LETTER P WITH STROKE THROUGH DESCENDER), not <U+0070 U+0331>.

**Comment by Alice196498** [comment]
It is. I was wondering about the title—thank you for mentioning it.

**Comment by ctrlcctrlv** [comment]
Oh! Now it makes sense to me, "&#xA751;&#x17F;ones" would be spelled "persons" in the modern orthography. At first I didn't know how to pronounce it. :-)

**Comment by Alice196498** [comment]
Yes. Ꝑ is an abbreviation of _per, par,_ or _por._ In _ꝑſones,_ it would be expanded to _per._

**Comment by ctrlcctrlv** [comment]
Yeah, sorry, on my system, P̱ is rendered correctly, but p̱ looks almost exactly like ꝑ, so I mixed them up when they are different.
