### ISSUE TITLE
Sequence “ longs_l ” poorly kerned/lacking ligature.

### ISSUE THREAD

**Issue by Alice196498** [ctrlcctrlv/kjv1611#29]
This is alſo the caſe with longs_longs_l, longs_b, and longs_k. I haven’t had a chance to review all letter pairs, but to my knowledge and what I did teſt, it ſeems that the kerning is otherwiſe ſerviceable.

**Comment by ctrlcctrlv** [comment]
I do see that I am missing the a `longs_l` ligature, oops! There also is something of a ligature, or maybe just an alternate `k`, in the sequence `longs k`, most easily seen in Psalms 114:4.

As for `longs b`, most often seen in the word "husband", e.g. in Numbers 5:20 or Genesis 3:6, it is sometimes very close and other times quite far, as shown below.

![husband num 5 20](https://user-images.githubusercontent.com/838783/53067362-db812900-350e-11e9-914f-e32842f81934.png)
![herhusband](https://user-images.githubusercontent.com/838783/53067370-de7c1980-350e-11e9-909c-cb17c1efbc8b.png)

**Comment by Alice196498** [comment]
I’m intereſted in this ligature or alternate k whereof you ſpeak. As for the longs_b, you’re right. It’s intereſting to not how they filed down the b in your ſecond image—this is a nice way to do it, I ſuppoſe, but it would have been time-conſuming. If you were to take the kerning approach, the firſt example in your image would be the beſt model, in my opinion, as the ſecond ſeems a little leſs nice to my eyes and ſenſibilities ; whereas if you were to take the other approach, either creating a filed-down b to go next to it (ſimilar to the alternate w that comes after an ſ ) or a ligature ſeems equally ſervicable, with the former being more accurate to this text, and the latter more agreeable to the general uniformity of the typeface.

**Comment by ctrlcctrlv** [comment]
![skipped](https://user-images.githubusercontent.com/838783/53222490-f9829100-36a8-11e9-8bac-043674e5e5b2.png)

`longs_k`&mdash;or `longs k.calt`&mdash;not sure which, but lean towards the latter as the correct interpretation.

**Comment by Alice196498** [comment]
longs_k would be the moſt proper if it’s a ligature, I think, but if it’s not a ligature, it would be an alternate, I ſuppoſe. It doeſn’t _look_ like a ligature, but it could be.
