### ISSUE TITLE
Non-gothic typeface in KJV

### ISSUE THREAD

**Issue by emacsomancer** [ctrlcctrlv/kjv1611#3]
What about the non-gothic, 'roman' type in the King James Version?  Do you know anything about which typeface was used in the 1611 edition? E.g.:
![such as](https://i.imgur.com/5WlgQOV.png)

(a number of interesting ligatures there too..)

**Comment by ctrlcctrlv** [comment]
@emacsomancer [EB Garamond](https://github.com/georgd/EB-Garamond) is recommended, I found it to be the closest of all the free ones in existence. 

Some of the italic swash caps are different, but the upright Roman letters are virtually identical.
