### ISSUE TITLE
No `mark` or `mkmk`

### ISSUE THREAD

**Issue by ctrlcctrlv** [ctrlcctrlv/kjv1611#33]
I made an error during the construction of this font which is now coming back to haunt me in some ways.

I used FontForge's automatic generation of letters with diacritics instead of generating them myself the right way via adding anchors and classes and using the OpenType `mark` feature. Part of why I did this was I was affected by fontforge/fontforge#3324&mdash;but I didn't know it and thought I was doing something wrong.

The effects of this are subtle. For one thing, combining diactritics don't work right in this font. This becomes glaringly obvious w/r/t #21, #25 etc., as I have added ligatures and extra glyphs encoded in the PUA instead of just allowing the renderer to render it correctly.

I will eventually have to scrap all my diactric letters and do them over again the right away. This issue will track my progress (if any :wink: ) with that.

**Comment by ctrlcctrlv** [comment]
Update: Discovered fontforge/fontforge#3482 today while working on this. Unfortunately we rely on a buggy software to build&hellip;maybe if the developers there merge fontforge/fontforge#3469 I'll see about trying to solve fontforge/fontforge#3482, but so far my PR's haven't oft been met with merges so I'll hold off for now&hellip;

Also, maybe I should consider putting `mark` and `mkmk` in the feature file [like this](https://glyphsapp.com/tutorials/mark-to-mark-positioning)

**Comment by Alice196498** [comment]
That feature file idea might be a good idea. I’ve heard of ſome people uſing MS VOLT for the OpenType features, but I’ve perſonally never been able to get it working, and while that would complicate things, it might be a ſolution to conſider.

**Comment by ctrlcctrlv** [comment]
I am a Linux diehard, but rather than dismiss your suggestion outright I figured, why not give it a try, despite having absolutely no experience with Microsoft VOLT?

![corrupted volt](https://user-images.githubusercontent.com/838783/53158781-62153380-35ff-11e9-9fda-f3eb295e9ccb.png)

Unfortunately, according to VOLT all the fonts on my system are corrupted. Perhaps a problem with Wine, but I have no idea how to investigate further. I'd prefer to stick with FontForge and `ttx`, despite their flaws, for now :-)

**Comment by ctrlcctrlv** [comment]
Crap. I can't build the font with https://github.com/ctrlcctrlv/kjv1611/commit/9d8c7ade530a7d903178cce5dfb1c683f0d993ac because of fontforge/fontforge#3435...so I have to choose either `mark` or `kern` :dizzy_face: 

`ttx -x GPOS` is too hamfisted. Need to find a more delicate solution&hellip;or this bug needs fixing.

**Comment by ctrlcctrlv** [comment]
Khaled Hosny of Sorts Mill fame saved me https://github.com/ctrlcctrlv/kjv1611/commit/05327dc73e7825c177d2f4e1384149953e6ae494

So now we can have both `mark` and `kern` living harmoniously together.

**Comment by ctrlcctrlv** [comment]
Fixed in v3.6.
