### ISSUE TITLE
Old style

### ISSUE THREAD

**Issue by DavidBCampbell2** [ctrlcctrlv/kjv1611#37]
I was wondering how to I switch to the long style S, in particular the medieval style? Thank you for your help!

**Comment by ctrlcctrlv** [comment]
It depends on the software you're using, how to enable OpenType Historical Forms. In LibreOffice for example, you set the font to `KJV1611:hist`. In Adobe products usually there's a button to press. There's not enough information for me to comment beyond that.

**Comment by DavidBCampbell2** [comment]
I don't see an option for KJV1611:hist in the list of fonts. I am using
Libre office.

**Comment by ctrlcctrlv** [comment]
You type it in directly. It's not well documented.

**Comment by Alice196498** [comment]
The rules for uſing it in this ſtyle are a little different from Roman type, but not very much. I could probably look into it and compile ſome documentation.

**Comment by ctrlcctrlv** [comment]
Sure, and as @Alice196498 notes, you can also use the Unicode characters directly, ſ, ꝛ, ⸗

**Comment by alerque** [comment]
Besides typing OpenType feature codes directly appending them to the font in the font name drop down list, you can also select features via tho Format → Character dialog box as shown here:

![image](https://user-images.githubusercontent.com/173595/110197534-30293f80-7e5d-11eb-8a38-257b9d995fdd.png)
