### ISSUE TITLE
Lowercase S styles

### ISSUE THREAD

**Issue by jsharpminor** [ctrlcctrlv/kjv1611#38]
Hello, and thank you for this wonderful font!

I don't know if I'm doing something wrong, but the lowercase letter "s" always appears as the "s"-shaped ligature modern readers are familiar with, rather than as an "f" missing the crossbar.

I have tried this in both Word and LibreOffice. I've tried it in the beginning, middle, and end of words. I've tried it as a double letter. I'm running Windows 10.

**Comment by kenmcd** [comment]
There are two ways to enable the long s with OpenType features.
hist - for Historical Forms, or
ss03 - Stylistic Set 03
So in LibreOffice you would change the font name to: **KJV1611:hist** or **KJV1611:ss03**
In Word you would have to enable Stylistic Set 3.

**Comment by ctrlcctrlv** [comment]
Yes
