### ISSUE TITLE
Small caps

### ISSUE THREAD

**Issue by artistofmind** [ctrlcctrlv/kjv1611#6]
A full set of OpenType small caps, to complement the LORD ligature.

**Comment by artistofmind** [comment]
Of low importance (provided the small caps can be inserted manually), you might consider adding a ligature for GOD as well. Because sometimes His name is written "the Loꝛd GOD," with the latter word small-capped rather than the former.

**Comment by ctrlcctrlv** [comment]
@artistofmind Wanted to make sure you saw the closes of these issues. Does the `c2sc` feature work for you? I assume you'll need to also apply some justification or use #7 to get the spacing right.

**Comment by artistofmind** [comment]
The new small caps are indeed present & correct. :) (Or at least as correct as the current capitals.) With two notable exceptions: the small-capped D should differ from the regular D in its center strokes & bottom-left corner (you already noticed this when you made the LORD ligature), and the small-capped R should be open at the top (you didn't notice this before; the ligature, too, should reflect this). Those are the only two differences of which I'm aware, but there may be others; I shall have to hunt for and crop all the small-capped phrases I can find, and see if I spot any other discrepancies. But if you compare the R & D in any instance of LORD with their full-sized counterparts, you'll see readily enough what I mean.
