### ISSUE TITLE
Punctuation spaces

### ISSUE THREAD

**Issue by artistofmind** [ctrlcctrlv/kjv1611#7]
A thin space (U+2009) and narrow no-break space (U+202F). To be manually inserted before colons, commas & question marks, as in the original Bible.

**Comment by Alice196498** [comment]
It would be better to create the full range of ſpaces (U+2000 – U+200B) and allow the uſer or typeſetting ſoftware handle the ſpacing. As the ſpacing is done manually in the Bible and other Works, an automatick ſolution at the fount level would be inſufficient for more delicate work and reproductions.

**Comment by artistofmind** [comment]
That is reasonable. I don't object to the inclusion of, say, em & en spaces as well. But I decided I'd be content with just the two spaces named above, because:
1. Justified alignment already apportions most of the whitespace accurately. The only real issue is when there is space to the left of (e.g.) a comma in the Bible, it's usually slightly less than the space to the right. A thinner-than-normal space is needed to achieve this effect.
2. On the other hand, wider-than-normal space can be achieved by just using (for example) two regular spaces, or a regular space + thin space.
3. I requested the NNBS specifically because I'd like it to be included as a non-breaking version of the same thing. (So a thin space that stays on the line with the word preceding it.) All the designer therefore needs to do is include two thin spaces, one that breaks and one that doesn't. I believe this would be sufficient.

**Comment by Alice196498** [comment]
You make ſome fair points ; however, it’s generally beſt to include the full ſet of ſpaces to allow things to be done with propriety, rather than cobble together a hack that’s “ good enough,” becauſe ſuch hacks lead to bad typeſetting practices. If a wider ſpace be wanting, it’s never good practice to ſet two regular ſpaces next to each other. In general, uſe one of the larger ſpaces, or ſet, for example, a thin ſpace and a regular, or an en and a regular ſpace. The non-breaking ſpaces are quite uſeful, and I fully endorſe their uſe when befitting the work.

**Comment by ctrlcctrlv** [comment]
How many units do you guys think each space should be? Fire up FontForge and let me know. :-) 

Should be an easy enough way for you to contribute. Every glyph window contains a ruler you can use.

**Comment by Alice196498** [comment]
The em ſpace (U+2003 U+2001) is the ſame ſize as the UPM ſize of the fount, which is uſually 1,000. The en ſpace (U+2002 U+2000) is half that at 500. The thick ſpace (U+2004) is ⅓ of the em, the middling ſpace (U+2005) is ¼ the em, the thin ſpace (U+2009 U+202F) is ⅕ an em, the ſix-per-em ſpace (U+2006) is ⅙ an em, and the hair ſpace can be anywhere between ⅛ and ⅟₁₆—I ſet it to ⅒ in my work, as I find that to be a nice ſize for it. The figure ſpace (U+2007) is the ſame ſize as the tabular numerals, the puctuation ſpace (U+2008) is the width of the period, the zero-width ſpace (U+200B) is 0. The medium mathematical ſpace is ⁴⁄₁₈ of an em.

**Comment by artistofmind** [comment]
I just wanted to say thank you, Alice, for your contribution to this thread. I can verify that the information in your latest comment is accurate; and your earlier comment, about good typographical practice, is a fount of wisdom. (Font of wisdom?) ;) When submitting this request, I was worried it would come across as excessively demanding -- I have been described by others as OCD, a perfectionist & a nerd -- but now I feel vindicated, supported & relieved. <3

**Comment by Alice196498** [comment]
I’m happy to help. When I realized I could contribute ſomething to the development of this fount, I could not forbear doing my everything in my power to be of aſſiſtance. This is eſſentially the only proper blackletter fount in the Engliſh ſtyle ; thus, as a typeſetter, I feel that it is important that I do what I can to help it be more complete and ſuited to doing well the various taſks which it may be employed. That’s why I poſted #14—I was conſidering not only the goal of the deſign, but alſo the potential to help many typeſetters who may be in great need of ſomething like this.
 As for my comment on good typographical practice, I ſtrive to typeſet things well ; thus, when doing ſo, it is of paramount importance that it be done with propriety—if one allows oneſelf to fall into bad practices, the work ſhall ſuffer for it : and, perhaps more importantly, it’ll make working with things much more difficult for everyone. It’s better to ſpend two extra minutes doing ſomething right than to do it in half that and ſpend an hour trying to fix it when ſomething goes wrong later. I’ve read many books on fine book-work and good practice, and I’ve alſo tried everything I’ve read there myſelf to make ſure it works, is effecient, and beneficial in our modern digital age. Good ſpacing is, in my opinion, one of the moſt important things to a work ; for without it, reading not only becomes more difficult, but it alſo hinders machine parſing, and takes control away from the perſon working with the text either as a reader, or, as a typeſetter. This is one reaſon I feel it’s ſo important to add the full ſet of ſpaces—it’s trivial to add, and allows much more freedom when working with the fount as a typeſetter and a reader.
 I’m aware that I am quite a perfectioniſt, & I have a tendancy to over-think things, but I do it with the beſt intentions of making things more beautiful, and more importantly, more functional and eaſier to work with. That is why I am honoured to be able to help with this, even if I can do little more than provide ſome information & ſuggeſtions.

**Comment by ctrlcctrlv** [comment]
The width of "M" is 957 units,* so:

(em) U+2003 / U+2001: 957 units
(en) U+2002 / U+2000: 957÷2 = 478.5 units
(thick) U+2004:  957÷3 = 319 units
(middling) U+2005: 957÷4 = 239.25 units
(thin) U+2009 / U+202F: 957÷5 = 191.4 units
(hair) U+200A: 957÷10 = 95.7 units
(6 per em) U+2006: 957÷6 = 159.5 units
(figure space doesn't apply as font has no tabular numerals at present)
(punctuation) U+2008: 217 units (width of period)
(zero width) U+200B: 0 units
(mathematical) U+205F: 957×⁴⁄₁₈ = 212⅔ units

\* FontForge units

You can expect all these spaces in sfnt revision 3.1.

**Comment by Alice196498** [comment]
In moſt modern founts, an em is ſet to the UPM ſize of the fount, rather than the width of the M character ; however, ſetting it to the ſame ſize as the M glyph works well enough moſt of the time—it’s beſt for it to be about a pica, though.

**Comment by ctrlcctrlv** [comment]
I'm going to use the width of the M if you don't mind, I'm not sure what the UPM size of my font is, or how to find out :wink:

**Comment by Alice196498** [comment]
According to [this,](http://designwithfontforge.com/en-US/The_EM_Square.html) “ You will find the ſetting in Element > Font Info..., on the PS Private tab.” The UPM ſize ſeems to be 775, which is ſtrange, as according to [this,](https://silnrsi.github.io/FDBP/en-US/Design_Metrics.html) the beſt practice is to ſet it to 2048 or 1000.

**Comment by ctrlcctrlv** [comment]
That page must be wrong because the PS Private tab is blank for me
![psprivate](https://user-images.githubusercontent.com/838783/50745425-0831f780-1265-11e9-830b-71a4d1609d30.png)
.

**Comment by ctrlcctrlv** [comment]
I do see the number 775 though in the **General** tab, it's marked "Em Size" in FontForge, not UPM size, perhaps they are the same thing :-)

**Comment by Alice196498** [comment]
Yes, they are the ſame thing.

**Comment by ctrlcctrlv** [comment]
Good news - I figured it out. I rescaled the font to 2048, and now no longer receive the "em size too small" warning. Width of "M" is now much larger though, 2528 units, so I'm going to add the space generation to `script.txt` which I run before font generation. The benefit of this is I can start using it in my other fonts too instead of doing manual calculation each time em size changes.

**Comment by Alice196498** [comment]
That’s one reaſon that the em is ſet to the ſame ſize as the the UPM of the fount—it helps keep the point ſizes and other things correct. It alſo enſures that different ſoftware gets the right value for the em ſquare.

**Comment by ctrlcctrlv** [comment]
Actually, I spoke too soon, FontForge seems to prefer 1000 as em instead of 2048, so am going with that :)

**Comment by Alice196498** [comment]
It’s true that many founts are ſet to 1000. Moſt I’ve worked with are ſo.

**Comment by ctrlcctrlv** [comment]
Thank you for your help by the way, I really appreciate it. Can I ask what fonts you've made?

**Comment by Alice196498** [comment]
I’m happy to help. I haven’t made any myſelf, but I do need to edit ſome I have from time to time. I tend to look carefully at how they’re done in order to better underſtand how to uſe them beſt. Typeſetting is a hobby of mine.
