### ISSUE TITLE
Numbers

### ISSUE THREAD

**Issue by artistofmind** [ctrlcctrlv/kjv1611#8]
1. Reduce the size of all numbers by approx. one point, till the x-height matches that of the letters, and the character weight is the same.
2. Some numbers could do with slight remastering. In particular:
- The "1" should be more symmetrical. (Not left to right, but top to bottom.) The top-right stroke is heavy; it gives this glyph a lopsided, unfinished look.
- The "2" has too square a taper on the bottom, and too blob-like a hook on top. It could be sharper. (A new source image may be needed; that scan doesn't look exemplary to me.)
- The "0" is thicker on the right than the left. In the Bible, it's a uniform circle.

**Comment by ctrlcctrlv** [comment]
You should be aware that these scans are all I have now. I donated my reproduction Bible to my church--it is currently being fitted to a display case so in a far off city from me so I cannot get new microscope images.

Nevertheless, flip through the glyphs and SVGs, they all came from the microscope I assure you. I looked at many examples of the same glyph before choosing one or two to image. The reproduction Bible's resolution is unfortunately not as high as it could be, you will see clear pixelation in the microscope scans.

If you have better images provide them.

**Comment by ctrlcctrlv** [comment]
Thanks to your e-mails I certainly see what you mean about my numbers being too thick, it's undeniable in the side-by-side comparisons. I'll see what I can do once I receive your scans.

**Comment by ctrlcctrlv** [comment]
I'm working on thinning numbers, they should appear in sfnt revision 3.2.

**Comment by ctrlcctrlv** [comment]
What do you think of this, @artistofmind ? The blue 2 is the current 2, and the red 2 is my proposed new thinner 2.

![223](https://user-images.githubusercontent.com/838783/51826707-ab38d700-2322-11e9-8b7a-aaeba97c0924.png)

**Comment by artistofmind** [comment]
Thanks for keeping me apprised of your progress; I’m sorry I didn’t notice this comment till now.

Well, it doesn’t yet look much thinner, at least in that picture. I’m also not finding that curve on the bottom (or the angle you originally had, for that matter). The bottoms of most 2s look straight to me; the uptick at the end of the descender is the only real curve I’m seeing (as opposed to a square notch like in both of yours). Also, I think the top-left tip of the hook should come to more of a point. That’s really the thickest-looking part in both your drawings.

That said, the overall shape of your second drawing is a general improvement. :) I suspect you just need to look at some additional source scans. I’ll include a few cropped 2s in my next email.

Reverse engineering a typeface from letterpresses in an olde booke is a uniquely challenging project, and you do very fine work, sir. Keep it up!

**Comment by artistofmind** [comment]
So, after looking at a great many 2s, I begin to suspect there may indeed be a slight curve on the bottom, as in your second version (more or less). But I still believe it’s meant to curve the other way on the top side of that bottom line, with a rounded “joint” before the uptick, rather than a square one, and a slight angle leading up toward the same, rather than curving down as in your second one (or angling down as in the first). Because I see it this way quite often. It seems the right edge of this particular glyph often stamps more clearly than the left, for some reason (as if the lead is right-heavy, or the ink’s likelier to pool there, or something). I also still think the tip of the hook is meant to continue to a point, because it often does; and where it appears snub-nosed, instead, it’s an artefact of the full shape not being reproduced in that particular pressing. Admittedly, it often shows up with a square right side and/or blunt left side; but the rest of the time it has the curve and/or point instead, or something in between these two extremes. So it’s actually hard to determine which is the artefact! But I suspect the snub-nosed 2 is likelier the flawed one, since its hook doesn’t continue as far, which is evidence it didn’t get enough ink, or contact the paper as fully. (I mean it would be harder to add length than subtract it, don’t you think?) As for the exact curve / angle of the bottom-right joint — I’ll let you decide, once you peruse the crops I’m currently compiling.

Based on what I’ve seen with the 2, I’ve concluded I’m going to need to crop many more numbers! I started by just focussing on capital letters, then decided to do the lowercase ones also, just because why not; but the numbers needed the most work to begin with, as you know. And cropping several hundred of each from various scanned pages, then comparing them all and selecting the cleanest specimens with the most features in common, plus deleting the blurriest / least complete ones, for every symbol, is extremely time consuming. But that’s why I’m doing this, in the first place: to save you time, which I know you could spend more productively after the fact (i.e. drawing rather than cropping). :) Once I feel I’ve successfully compiled a representative sample of quality letterpresses for each symbol that occurs in the Bible (excluding the Garamond, ornaments or drop caps, of course), I’ll share the result with you, and you can add them to the master collection, and compare each of your letters side-by-side with them (I’ll make more screenshots doing this, too, as already promised). It should be quite revealing, and may show you a few details missing from your current samples.

That said, this is going to take me the rest of the week, at least. :( The deadlines I keep setting for myself fall away as I discover whole new characters, or aspects of characters, I have to now hunt for more good examples of. I’m also trying to determine how often they all occur one way or another. (The capital J is a great example of this: the exact length & shape of its descender seems slightly different every single time it occurs! I also suspect there’s meant to be at least one contextual alternate depending on if there’s a tall ascender right beneath it. But I’ve even spotted a few of what appear to be “vertical ligatures” — you’ll see what I mean soon enough. You may just have to include several different Js, to be selected at the user’s discretion.) Also, every time I read the Bible, I discover something else I need to crop. ^_^;; So this project is temporarily overlapping / interfering with my study time. ;( Finally, while I wish I could do nothing but this all day long, I do have other responsibilities, too!

So anyway, I’m sorry it’s taking me so long to get my work to you. I really believe this is worth doing though, and am happy to do it for you. Doing it right is what takes so long; naturally, if I didn’t do it right, there’d be no point in doing it at all, since I don’t intend to send you any half-formed or blurry crops, only the best examples I can find. But nearly all of them are flawed in one way or another, and finding & sorting the best takes hours & hours. . . . That said, while I’m still just cropping whatever I spot that looks good at the moment, once I feel I’ve finished with some letters but not others, I may just start sending my work to you in batches. We shall see!

Your prayers would be appreciated; mine are already with you. Take care, Brother Brennan.
